# Generated by Django 2.2 on 2019-06-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roll', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['roll'],
            },
        ),
    ]
