# Generated by Django 2.2 on 2019-06-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Accion'), ('2', 'Romantic'), ('3', 'Scient Ficcion'), ('4', 'Humor')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movieraiting',
            name='vote',
            field=models.CharField(blank=True, choices=[('1', 'I Like'), ('2', 'I Dont Like')], default=None, max_length=1),
        ),
    ]
