# Generated by Django 2.2.2 on 2019-06-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovie', '0002_auto_20190610_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
