# Generated by Django 2.2.2 on 2019-06-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovie', '0004_auto_20190614_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=''),
        ),
    ]
