# Generated by Django 2.2.2 on 2019-06-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovie', '0006_auto_20190616_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
