# Generated by Django 2.2.2 on 2019-06-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovie', '0008_auto_20190617_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
