# Generated by Django 2.2.2 on 2019-06-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovie', '0014_auto_20190617_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieraiting',
            name='comment',
            field=models.TextField(default=None),
        ),
    ]
