# Generated by Django 2.2.2 on 2019-06-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovie', '0015_auto_20190617_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieraiting',
            name='vote',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, max_length=1),
        ),
    ]
