# Generated by Django 2.2.2 on 2019-06-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmovie', '0022_auto_20190617_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieraiting',
            old_name='id_movie_name',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movieraiting',
            old_name='id_user_django',
            new_name='user',
        ),
    ]
