# Generated by Django 2.2.2 on 2019-06-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovie', '0024_auto_20190617_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieraiting',
            name='comment',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
