# Generated by Django 2.2.2 on 2019-06-18 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appmovie', '0026_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={},
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
